apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sheldrinzhu-sheldrinzhu-poi-map-app-dev
  annotations:
    argocd/app-name: sheldrinzhu-sheldrinzhu-poi-map-app-dev
    backstage.io/kubernetes-id: sheldrinzhu-sheldrinzhu-poi-map-app-dev
    backstage.io/kubernetes-namespace: sheldrinzhu
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=sheldrinzhu-sheldrinzhu-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/sheldrinzhu-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/sheldrinzhu/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/sheldrinzhu/deployments/sheldrinzhu-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/sheldrinzhu-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://sheldrinzhu-poi-map-app-sheldrinzhu.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "default:default/sheldrinzhu"
  system: workshop-system-sheldrinzhu
  consumesApis:
    - gateway-api-sheldrinzhu
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-sheldrinzhu
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "default:default/sheldrinzhu"
